Build: Update nan version dependency
The recent commits which change dependencies of Nan::ForceSet() to
Nan::DefineOwnProperty() require an update to Nan dependencies otherwise an
error of `error: no member named 'DefineOwnProperty' in namespace 'Nan'` is
thrown.

Closes gh-163